/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RegisterController;
import javax.swing.ImageIcon;
import model.KhachHang;

/**
 *
 * @author A715-42G
 */
public class RegisterView extends javax.swing.JFrame {

    RegisterController rAC = new RegisterController();

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon(this.getClass().getResource("/assets/img/burger.png"));
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        pasPass = new javax.swing.JPasswordField();
        pasCPass = new javax.swing.JPasswordField();
        txtAcc = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jlbAcc = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbPass = new javax.swing.JLabel();
        jlbCPass = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jlbPhone = new javax.swing.JLabel();
        anhNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký");
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 40, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 60, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Xác nhận mật khẩu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 120, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên đăng nhập");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));

        btnRegister.setText("Đăng ký");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, -1));
        getContentPane().add(pasPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 140, -1));
        getContentPane().add(pasCPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 140, -1));
        getContentPane().add(txtAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 140, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/nBack3.jpg"))); // NOI18N
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setMaximumSize(new java.awt.Dimension(29, 29));
        btnBack.setMinimumSize(new java.awt.Dimension(26, 26));
        btnBack.setPreferredSize(new java.awt.Dimension(29, 29));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jlbAcc.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jlbEmail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jlbPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jlbCPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbCPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Họ tên");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Số điện thoại");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jlbName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 140, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, -1));

        jlbPhone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        anhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/register.jpg"))); // NOI18N
        anhNen.setToolTipText("");
        getContentPane().add(anhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        LoginView l = new LoginView();
        l.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        String tenKH = txtName.getText();
        String email = txtEmail.getText();
        String soDT = txtPhone.getText();
        String tenDN = txtAcc.getText();
        String matKhau = pasPass.getText();
        String cMatKhau = pasCPass.getText();
        KhachHang kh = new KhachHang(tenDN, tenKH, matKhau, soDT, email);

        rAC.register(kh, this, cMatKhau, jlbName, jlbEmail, jlbPhone, jlbPass, jlbCPass);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhNen;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbAcc;
    private javax.swing.JLabel jlbCPass;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbName;
    private javax.swing.JLabel jlbPass;
    private javax.swing.JLabel jlbPhone;
    private javax.swing.JPasswordField pasCPass;
    private javax.swing.JPasswordField pasPass;
    private javax.swing.JTextField txtAcc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
